# Object files to either reference or create
OBJECTS = main.o
# The executable file that will be created at the end
EXEC = day_1.5
# The flags to use for compilation
CXXFLAGS = -g -Wall
# The code compiler to use for compilation
CXX = g++
# Perform action on all object files (May or may not exist)
all: $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(EXEC) $(OBJECTS)
